server:
  port: 5050
  servlet:
    context-path: /api

#数据库配置信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Lcx0618.
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
  #redis配置
  redis:
    host: localhost
    port: 6379

#minio配置